const legacyChain = [
  'moonbeam',            'aleph',           'astar',
  'acala',               'alephTest',       'aventus',
  'moonbase',            'bifrost_dot',     'bifrost_testnet',
  'calamari',            'amplitude',       'amplitude_test',
  'clover',              'hydradx_main',    'edgeware',
  'centrifuge',          'interlay',        'nodle',
  'darwinia2',           'sora_ksm',        'polkadex',
  'composableFinance',   'phala',           'crust',
  'karura',              'kilt',            'basilisk',
  'altair',              'kintsugi',        'picasso',
  'zeitgeist',           'shadow',          'robonomics',
  'crabParachain',       'chainx',          'acala_testnet',
  'mangatax_para',       'origintrail',     'kabocha',
  'ternoa',              'pendulum',        'kilt_peregrine',
  'xx_network',          'frequency',       'ipci',
  'shiden',              'logion',          'polymesh',
  'sora_substrate',      'joystream',       'krest_network',
  'deeper_network',      'energy_web_x',    'manta_network',
  'polimec',             'xcavate',         'energy_web_x_testnet',
  'energy_web_x_rococo', 'liberlandTest',   'liberland',
  'tangleTest',          'dentnet',         'hydradx_rococo',
  'creditcoinTest',      'acurast',         'humanode',
  'dbcchain',            'availTuringTest', 'avail_mainnet',
  'curio',               'peaq',            'cere',
  'creditcoin_native',   'tangle',          'jamton',
  'truth_network'
];
